spring:
  application:
    name: mediapi
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # current active profiles (local, dev, prod)
  profiles:
    active: local

#mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.medi.mediapi.project.*