spring:
  application:
    name: mediapi
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      # medi_clinic_manage
      clinic-dev:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://211.37.179.59:3306/?serverTimezone=UTC&characterEncoding=UTF-8
        username: medi_clinic
        password: "medi_clinic12#"
        keepaliveTime: 30000
        maximum-pool-size: 3
        pool-name: "[DEV]CLINIC_POOL"
